### ISSUE TITLE
could you add license ?

### ISSUE THREAD

**Issue by zoomer-k** [gmlarumbe/tree-sitter-systemverilog#1]
thank you for  openning for public .

I want to try this grammar.js but not including lisence file.

could you add lisence file for this repository. if you could?

**Comment by gmlarumbe** [comment]
Hi @zoomer-k ,

I am sorry I have been a bit busy lately and I did not have the time to check this... Thanks for reminding me of the license. It has been added in d4f44ea

Thanks a lot!
